# Generated by Django 4.2.7 on 2023-11-11 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 11, 16, 17, 14, 831780, tzinfo=datetime.timezone.utc), help_text='Дата окончания', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 11, 16, 17, 14, 831780, tzinfo=datetime.timezone.utc), help_text='Дата окончания работы', verbose_name='Дата окончания работы'),
        ),
    ]
