# Generated by Django 4.2.7 on 2023-11-12 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 11, 34, 54, 204837, tzinfo=datetime.timezone.utc), help_text='Дата окончания', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 11, 34, 54, 203741, tzinfo=datetime.timezone.utc), help_text='Дата окончания работы', verbose_name='Дата окончания работы'),
        ),
    ]
