# Generated by Django 4.2.7 on 2023-11-11 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='diplom_link',
            field=models.CharField(blank=True, help_text='Ссылка на проект/дипломную работу', null=True, verbose_name='Ссылка на проект/дипломную работу'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 11, 16, 28, 48, 761979, tzinfo=datetime.timezone.utc), help_text='Дата окончания', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='education',
            name='faculty',
            field=models.CharField(blank=True, help_text='Ваш факультет', max_length=150, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 11, 16, 28, 48, 761979, tzinfo=datetime.timezone.utc), help_text='Дата окончания работы', null=True, verbose_name='Дата окончания работы'),
        ),
    ]
