# Generated by Django 4.2.7 on 2023-11-12 11:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='diplom_link',
            new_name='diploma_link',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 11, 54, 52, 695628, tzinfo=datetime.timezone.utc), help_text='Дата окончания', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 11, 54, 52, 695628, tzinfo=datetime.timezone.utc), help_text='Дата окончания работы', null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='web_page',
            field=models.URLField(blank=True, help_text='Ссылка на сайт организации', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Укажите номер телефона для связи', max_length=12, validators=[django.core.validators.RegexValidator(message='Проверьте корректно ли указан номер телефона', regex='^[+7|8]\\d{10}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='telegram',
            field=models.CharField(blank=True, help_text='Аккаунт в Telegram. Начинается с @', validators=[django.core.validators.RegexValidator(message='Первый символ @, затем от 5 до 32 символов.', regex='^[@][a-z0-9_]{6,33}+$')], verbose_name='Telegram'),
        ),
    ]
