# Generated by Django 4.2.7 on 2023-11-12 12:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='education',
            name='check_education_end_date',
        ),
        migrations.RemoveConstraint(
            model_name='employmenthistory',
            name='check_work_end_date',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 12, 13, 21, 96481, tzinfo=datetime.timezone.utc), help_text='Дата окончания', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 12, 13, 21, 96481, tzinfo=datetime.timezone.utc), help_text='Дата окончания работы', null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Укажите номер телефона для связи', validators=[django.core.validators.RegexValidator(message='Проверьте корректно ли указан номер телефона', regex='^[+7|8]\\d{10}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='telegram',
            field=models.CharField(blank=True, help_text='Аккаунт в Telegram. Начинается с @', validators=[django.core.validators.RegexValidator(message='Первый символ @, затем от 5 до 32 символов.', regex='^[@][a-z0-9_]{6,33}$')], verbose_name='Telegram'),
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='check_education_end_date', violation_error_message='Дата окончания обучения должна быть позже начала!'),
        ),
        migrations.AddConstraint(
            model_name='employmenthistory',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='check_work_end_date', violation_error_message='Дата окончания работы должна быть позже начала!'),
        ),
    ]
