# Generated by Django 4.2.7 on 2023-11-12 16:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_education_check_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'default_related_name': 'courses', 'ordering': ('-date',), 'verbose_name': 'Повышение квалификации', 'verbose_name_plural': 'Повышение квалификации'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'default_related_name': 'about', 'verbose_name': 'О себе', 'verbose_name_plural': 'О себе'},
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 16, 6, 21, 390671, tzinfo=datetime.timezone.utc), help_text='Дата окончания', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 16, 6, 21, 390671, tzinfo=datetime.timezone.utc), help_text='Дата окончания работы', null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Укажите номер телефона для связи', validators=[django.core.validators.RegexValidator(message='Проверьте корректно ли указан номер телефона', regex='^(\\+?7|8)([\\d]{7,10})$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='telegram',
            field=models.CharField(blank=True, help_text='Аккаунт в Telegram. Начинается с @', validators=[django.core.validators.RegexValidator(message='Первый символ @, затем от 5 до 32 символов.', regex='^[@][\\D\\d_]{5,32}$')], verbose_name='Telegram'),
        ),
    ]
