# Generated by Django 4.2.7 on 2023-11-12 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_courses_options_alter_information_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 16, 8, 8, 272510, tzinfo=datetime.timezone.utc), help_text='Дата окончания', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 12, 16, 8, 8, 272510, tzinfo=datetime.timezone.utc), help_text='Дата окончания работы', null=True, verbose_name='Дата окончания работы'),
        ),
    ]
