# Generated by Django 4.2.7 on 2023-12-05 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_resumeuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Укажите номер телефона для связи', validators=[django.core.validators.RegexValidator(message='Проверьте корректно ли указан номер телефона', regex='^([+7]|[8])[\\d]{7,11}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='telegram',
            field=models.CharField(blank=True, help_text='Аккаунт в Telegram. Начинается с @', validators=[django.core.validators.RegexValidator(message='Первый символ @, затем от 5 до 32 символов.', regex='^[@][a-zA-Z\\d_]{5,32}$')], verbose_name='Telegram'),
        ),
    ]
