# Generated by Django 4.2.7 on 2023-11-22 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_resumeuser_phone_alter_resumeuser_telegram'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='resumeuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='resumeuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Check first name', regex='^[а-яА-ЯёЁ\\s-]{2,50}$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Check last name', regex='^[а-яА-ЯёЁ\\s-]{2,50}$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter your phone number', max_length=12, validators=[django.core.validators.RegexValidator(message='Check phone number', regex='^+[0-9]{10,12}$')], verbose_name='phone number'),
        ),
    ]
