# Generated by Django 4.2 on 2023-11-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_resumeuser_phone_alter_resumeuser_telegram'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='resumeuser',
            managers=[
            ],
        ),
    ]
