# Generated by Django 4.2 on 2023-11-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_resumeuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeuser',
            name='username',
        ),
    ]
