version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: evol93/backend_resume:latest
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    image: evol93/frontend_resume:latest
    volumes:
      - ../frontend/:/app/build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/etc/nginx/html/static/
      - media_value:/etc/nginx/html/static/
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
