# Generated by Django 4.2.7 on 2023-11-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_status', models.CharField(choices=[('Активно ищу работу', 'Активно ищу работу'), ('Расммотрю предложения', 'Расммотрю предложения'), ('В творческом поиске', 'В творческом поиске')], help_text='Статус поиска', max_length=150, verbose_name='Статус поиска')),
                ('position', models.CharField(help_text='Должность', max_length=150, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resume_images/', verbose_name='Фото')),
                ('video_link', models.CharField(blank=True, help_text='Видео с соискателем', max_length=150, null=True, verbose_name='Видео презентация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150, verbose_name='Навык')),
                ('profession', models.CharField(blank=True, max_length=150, null=True, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('GitHub', 'GitHub'), ('Behance', 'Behance'), ('Habr', 'Habr'), ('Персональная страничка', 'Персональная страничка'), ('StackOverflow', 'StackOverflow')], help_text='Название сайта', max_length=150, verbose_name='Интернет-ресурс')),
                ('web_page', models.CharField(help_text='Ссылка', max_length=150, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Ссылка на ресурс',
                'verbose_name_plural': 'Ссылки на ресурсы',
                'ordering': ('link_type',),
            },
        ),
        migrations.AddConstraint(
            model_name='weblink',
            constraint=models.UniqueConstraint(fields=('link_type', 'web_page'), name='unique_acount'),
        ),
        migrations.AddField(
            model_name='resume',
            name='about',
            field=models.ManyToManyField(to='user.information', verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='resume',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='resume',
            name='courses',
            field=models.ManyToManyField(to='user.courses', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(to='user.education', verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(to='user.projects', verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='resume.skills', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='resume',
            name='web_page',
            field=models.ManyToManyField(to='resume.weblink', verbose_name='Ссылки на свои ресурсы'),
        ),
        migrations.AddField(
            model_name='resume',
            name='works',
            field=models.ManyToManyField(to='user.employmenthistory', verbose_name='Место работы'),
        ),
    ]
