# Generated by Django 4.2.7 on 2023-11-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('search_status', models.CharField(blank=True, choices=[('Активно ищу работу', 'Активно ищу работу'), ('Рассмотрю предложения', 'Рассмотрю предложения'), ('В творческом поиске', 'В творческом поиске')], help_text='Статус поиска', max_length=150, verbose_name='Статус поиска')),
                ('position', models.CharField(help_text='Должность', max_length=150, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, upload_to='resume_images/', verbose_name='Фото')),
                ('video_link', models.URLField(blank=True, help_text='Ссылка на видео с соискателем', max_length=150, verbose_name='Видео презентация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ('-created_at',),
                'default_related_name': 'resume',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150, verbose_name='Навык')),
                ('profession', models.CharField(blank=True, choices=[('Проектный менеджер', 'Проектный менеджер'), ('Системный аналитик', 'Системный аналитик'), ('UX/UI дизайнер', 'UX/UI дизайнер'), ('Frontend разработчик', 'Frontend разработчик '), ('Backend разработчик', 'Backend разработчик '), ('Тестировщик', 'Тестировщик ')], max_length=150, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GitHub', 'GitHub'), ('Behance', 'Behance'), ('Habr', 'Habr'), ('Персональная страничка', 'Персональная страничка'), ('StackOverflow', 'StackOverflow')], help_text='Название сайта', max_length=150, verbose_name='Интернет-ресурс')),
                ('web_page', models.URLField(help_text='Ссылка', max_length=2000, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Ссылка на ресурс',
                'verbose_name_plural': 'Ссылки на ресурсы',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='weblink',
            constraint=models.UniqueConstraint(fields=('name', 'web_page'), name='unique_resource'),
        ),
    ]
