# Generated by Django 4.2.7 on 2023-11-27 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='about',
            field=models.ManyToManyField(blank=True, to='user.information', verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='resume',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='resume',
            name='courses',
            field=models.ManyToManyField(blank=True, to='user.courses', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(blank=True, to='user.education', verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(blank=True, to='user.projects', verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resume.skills', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='resume',
            name='web_page',
            field=models.ManyToManyField(blank=True, to='resume.weblink', verbose_name='Ссылки на свои ресурсы'),
        ),
        migrations.AddField(
            model_name='resume',
            name='works',
            field=models.ManyToManyField(blank=True, to='user.employmenthistory', verbose_name='Место работы'),
        ),
    ]
