# Generated by Django 4.2.7 on 2023-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='video_link',
            field=models.URLField(blank=True, help_text='Видео с соискателем', max_length=150, verbose_name='Видео презентация'),
        ),
    ]
