# Generated by Django 4.2.7 on 2023-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_education_end_date_and_more'),
        ('resume', '0002_alter_resume_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.ManyToManyField(blank=True, to='user.information', verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='courses',
            field=models.ManyToManyField(blank=True, to='user.courses', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(blank=True, to='user.education', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(blank=True, to='user.projects', verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='search_status',
            field=models.CharField(blank=True, choices=[('Активно ищу работу', 'Активно ищу работу'), ('Рассмотрю предложения', 'Рассмотрю предложения'), ('В творческом поиске', 'В творческом поиске')], help_text='Статус поиска', max_length=150, verbose_name='Статус поиска'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resume.skills', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='video_link',
            field=models.URLField(blank=True, help_text='Ссылка на видео с соискателем', max_length=150, verbose_name='Видео презентация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='web_page',
            field=models.ManyToManyField(blank=True, to='resume.weblink', verbose_name='Ссылки на свои ресурсы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='works',
            field=models.ManyToManyField(blank=True, to='user.employmenthistory', verbose_name='Место работы'),
        ),
    ]
