# Generated by Django 4.2.7 on 2023-11-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_about_alter_resume_courses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weblink',
            options={'ordering': ('id',), 'verbose_name': 'Ссылка на ресурс', 'verbose_name_plural': 'Ссылки на ресурсы'},
        ),
    ]
